---
title: "Final SQL Lab and Homework"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center')
```
  
**Duration - 180 minutes**  
  
In these practice questions you'll return again to the `omni_pool` database, so re-establish your connection in `DBeaver` if it has lapsed.

<br>
<div class='emphasis'>
**Submission**

When answering these questions, please save your `SQL` script in `DBeaver`, copy it over to your homework repo and then add, commit and push that for submission tonight. Please add section and question numbers as `SQL` comments, like so:

```{sql, eval=FALSE}
--MVP
--Q1
```
</div>
<br>

# MVP

<br>

**Question 1.**\
Are there any pay_details records lacking both a `local_account_no` and `iban` number?


<br>

**Question 2.**\
Get a table of employees `first_name`, `last_name` and `country`, ordered alphabetically first by `country` and then by `last_name` (put any `NULL`s last).

<br>

**Question 3.**\
Find the details of the top ten highest paid employees in the corporation.

<br>

**Question 4.**\
Find the `first_name`, `last_name` and `salary` of the lowest paid employee in Hungary.

<br>

**Question 5.**\
Find all the details of any employees with a 'yahoo' `email` address?

<br>

**Question 6.**\
Obtain a count by `department` of the employees who started work with the corporation in 2003.  

<br>

**Question 7.**\
Obtain a table showing `department`, `fte_hours` and the number of employees in each department who work each `fte_hours` pattern. Order the table alphabetically by `department`, and then in ascending order of `fte_hours`. 
<br><br>
<details>
<summary>**Hint**</summary>
You need to `GROUP BY` two columns here.
</details>

<br>

**Question 8.**\
Provide a breakdown of the numbers of employees enrolled, not enrolled, and with unknown enrollment status in the corporation pension scheme.

<br>

**Question 9.**\
What is the maximum `salary` among those employees in the 'Engineering' department who work 1.0 full-time equivalent hours (`fte_hours`)?

<br>

**Question 10.**\
Get a table of `country`, number of employees in that country, and the average `salary` of employees in that country for any countries in which more than 30 employees are based. Order the table by average `salary` descending.  
<br><br>
<details>
<summary>**Hints**</summary>  
A `HAVING` clause is needed to filter using an aggregate function.
<br><br>
You can pass a column alias to `ORDER BY`.
</details>

<br>

**Question 11.**\
Return a table containing each employees `first_name`, `last_name`, full-time equivalent hours (`fte_hours`), `salary`, and a new column `effective_yearly_salary` which should contain `fte_hours` multiplied by `salary`.

<br>

**Question 12.**\
Find the first name and last name of all employees who lack a `local_tax_code`.  
<br><br>
<details>
<summary>**Hint**</summary>  
`local_tax_code` is a field in table `pay_details`, and `first_name` and `last_name` are fields in table employees, so this query requires some sort of `JOIN`!
</details>

<br>

**Question 13.**\
The `expected_profit` of an employee is defined as (48 * 35 * `charge_cost` - `salary`) * `fte_hours`, where `charge_cost` depends upon the team to which the employee belongs. Get a table showing `expected_profit` for each employee.  
<br><br>
<details>
<summary>**Hints**</summary> 
`charge_cost` is in `teams`, while `salary` and `fte_hours` are in `employees`, so a join will be necessary
<br><br>
You will need to change the type of `charge_cost` in order to perform the calculation
</details>

<br>

**Question 14.**\
Obtain a table showing any `department`s in which there are two or more employees lacking a stored first name. Order the table in descending order of the number of employees lacking a first name, and then in alphabetical order by `department`.

<br>

**Question 15.**\
[**Bit Tougher**] Return a table of those employee `first_name`s shared by more than one employee, together with a count of the number of times each `first_name` occurs. Omit employees without a stored `first_name` from the table. Order the table descending by count, and then alphabetically by `first_name`.

<br>

**Question 16.**\
[**Tough**] Find the proportion of employees in each department who are `grade` 1.
<br><br>
<details>
<summary>**Hints**</summary>
Think of the desired proportion for a given `department` as the number of employees in that department who are `grade` 1, divided by the total number of employees in that department.  
<br><br>
You can write an expression in a `SELECT` statement, e.g. `grade = 1`. This would result in `BOOLEAN` values.  
<br><br>
If you could convert `BOOLEAN` to `INTEGER` 1 and 0, you could sum them. The `CAST()` function lets you convert data types.  
<br><br>
In `SQL`, an `INTEGER` divided by an `INTEGER` yields an `INTEGER`. To get a `REAL` value, you need to convert the top, bottom or both sides of the division to `REAL`.  
</details>

<br>

# Extension

Some of these problems may need you to do some online research on `SQL` statements we haven't seen in the lessons up until now... Don't worry, we'll give you pointers, and it's good practice looking up help and answers online, data analysts and programmers do this all the time! If you get stuck, it might also help to sketch out a rough version of the table you want on paper (the column headings and first few rows are usually enough). 

Note that some of these questions may be best answered using CTEs or window functions: have a look at the optional lesson included in today's notes!

**Question 17.**\
[**Tough**] Get a list of the `id`, `first_name`, `last_name`, `department`, `salary` and `fte_hours` of employees in the **largest** department. Add two extra columns showing the ratio of each employee's `salary` to that department's average `salary`, and each employee's `fte_hours` to that department's average `fte_hours`.  
<br><br>
[**Extension** - how could you generalise your query to be able to handle the fact that two or more departments may be **tied** in their counts of employees. In that case, we probably don't want to arbitrarily return details for employees in just one of these departments].
<br><br>
<details>
<summary>**Hints**</summary> 
Writing a CTE to calculate the name, average `salary` and average `fte_hours` of the largest department is an efficient way to do this.
<br><br>
Another solution might involve combining a subquery with window functions.
</details>

<br>

**Question 18.**\
Have a look again at your table for MVP question 8. It will likely contain a blank cell for the row relating to employees with 'unknown' pension enrollment status. This is ambiguous: it would be better if this cell contained 'unknown' or something similar. Can you find a way to do this, perhaps using a combination of `COALESCE()` and `CAST()`, or a `CASE` statement?  
<br><br>
<details>
<summary>**Hints**</summary>
`COALESCE()` lets you substitute a chosen value for `NULL`s in a column, e.g. `COALESCE(text_column, 'unknown')` would substitute `'unknown'` for every `NULL` in `text_column`. The substituted value has to match the **data type** of the column otherwise `PostgreSQL` will return an error.
<br><br>
`CAST()` let's you change the data type of a column, e.g. `CAST(boolean_column AS VARCHAR)` will turn `TRUE` values in `boolean_column` into text `'true'`, `FALSE` to text `'false'`, and will leave `NULL`s as `NULL`
</details>

<br>

**Question 19.**\
Find the first name, last name, email address and start date of all the employees who are members of the 'Equality and Diversity' committee. Order the member employees by their length of service in the company, longest first.

<br>

**Question 20.**\
**[Tough!]** Use a `CASE()` operator to group employees who are members of committees into `salary_class` of `'low'` (`salary < 40000)` or `'high'` (`salary >= 40000`). A `NULL` `salary` should lead to `'none'` in `salary_class`. Count the number of committee members in each `salary_class`.  
<br><br>
<details>
<summary>**Hints**</summary>
You likely want to count `DISTINCT()` employees in each `salary_class`
<br><br>
You will need to `GROUP BY salary_class`
</details>

